# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3628af57203dd6b96bc8a816d5b58d7ffa3e224e33e1befd2106d66e9d3f81cba9ceb5059a7b7ec307b9c93fb9d4552ce031fb88f5d38a3751ea40314a2251ef

test:
  secret_key_base: 8fb284853b5577a69520e633f968c1ac915dceb993e171992d8e434ff5b8772c400bfcd3cfe60ead84273124b73aeb4d1c06d873193314f193fec56e15d6b1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
